const Map<String, String> ar = {
  "language": "العربية",
  "home": "القائمة",
  "orders": "الطلبات",
  "address": "العنوان",
  "discount": "تخفيضات",
  "setting": "الاعدادات",
  "help": "مساعدة",
  "about": "عن التطبيق",
  "copyright": "حقوق الملكية © 2019 جميع الحقوق محفوظة ",
  "faq": "اسئلة و اجوبة \nالشروط و الاحكام",
  "login": "تسجيل الدخول",
  "enterPhone": "ادخل رقم الهاتف...",
  "skip": "تخطي",
  "gender": "النوع",
  "male": "ذكر",
  "female": "انثي",
  "feedYourHunger": "غذي\nجوعك",
  "easeOrdering": "سهولة\nفي الطلب",
  "dealsCoupon": "عروض\nوخصومات",
  "fastDelivery": "توصيل\nسريع",
  "done": "تأكيد",
  "resendCode": "اعاده ارسال الكود!",
  "exploreMenu": "تصفح القائمة",
  "sandwich": "الساندويتش",
  "dessert": "الحلويات",
  "meal": "الوجبات",
  "createOwnSandwich": "اصنع الساندوتش\nالخاص بك!",
  "createOwnSalad": "اصنع السلطة\nالخاصة بك!",
  "topMeal": "اروع الوجبات",
  "latestOrder": "الطلبات الاخيرة",
  "reorder": "اعادة الطلب",
  "location": "العنوان: ",
  "iamHungry": "انا جائع ",
  "toEat": "للأكل...",
  "previousOrder": "الطلبات السابقة",
  "hello": "مرحبا,"
};
