const Map<String, String> en = {
  "language": "english",
  "home": "Home",
  "orders": "Orders",
  "address": "Address",
  "discount": "Discount",
  "setting": "Setting",
  "help": "Help!",
  "about": "About Us",
  "copyright": "Copyright © 2019 All Right Reserved",
  "faq": "FAQs\nTerms&Condition",
  "login": "Login",
  "enterPhone": "Enter your phone number...",
  "skip": "Skip",
  "gender": "Gender",
  "male": "Male",
  "female": "Female",
  "feedYourHunger": "Feed your\nhunger",
  "easeOrdering": "Easy\nOrdering",
  "dealsCoupon": "Deals\n&Coupon",
  "fastDelivery": "Fast\nDelivery",
  "done": "Done",
  "resendCode": "Resend Code!",
  "exploreMenu": "Explore Menu",
  "sandwich": "Sandwich",
  "dessert": "Dessert",
  "meal": "Meals",
  "createOwnSandwich": "Create your Own\nSandwich!",
  "createOwnSalad": "Create your Own\nSalad!",
  "topMeal": "Top Meal",
  "latestOrder": "Latest Order",
  "reorder": "Reorder",
  "location": "Location: ",
  "iamHungry": "I'm Hungry",
  "toEat": "to Eat...",
  "previousOrder": "Previous Order",
  "hello": "Hello,",
  "": "",
};
